/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class GetSpeedActionResult : ActionResult<GetSpeedResult>
    {
        public const string RosMessageName = "isaacs_server/GetSpeedActionResult";

        public GetSpeedActionResult() : base()
        {
            this.result = new GetSpeedResult();
        }

        public GetSpeedActionResult(Header header, GoalStatus status, GetSpeedResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
