/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class GetSpeedResult : Message
    {
        public const string RosMessageName = "isaacs_server/GetSpeedResult";

        public float speed { get; set; }
        public uint id { get; set; }
        public bool success { get; set; }
        public string message { get; set; }

        public GetSpeedResult()
        {
            this.speed = 0.0f;
            this.id = 0;
            this.success = false;
            this.message = "";
        }

        public GetSpeedResult(float speed, uint id, bool success, string message)
        {
            this.speed = speed;
            this.id = id;
            this.success = success;
            this.message = message;
        }
    }
}
