/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class GetSpeedGoal : Message
    {
        public const string RosMessageName = "isaacs_server/GetSpeedGoal";

        public uint id { get; set; }

        public GetSpeedGoal()
        {
            this.id = 0;
        }

        public GetSpeedGoal(uint id)
        {
            this.id = id;
        }
    }
}
