/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class SetSpeedAction : Action<SetSpeedActionGoal, SetSpeedActionResult, SetSpeedActionFeedback, SetSpeedGoal, SetSpeedResult, SetSpeedFeedback>
    {
        public const string RosMessageName = "isaacs_server/SetSpeedAction";

        public SetSpeedAction() : base()
        {
            this.action_goal = new SetSpeedActionGoal();
            this.action_result = new SetSpeedActionResult();
            this.action_feedback = new SetSpeedActionFeedback();
        }

    }
}
