/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class SetSpeedFeedback : Message
    {
        public const string RosMessageName = "isaacs_server/SetSpeedFeedback";

        //  Define a feedback message (progress)
        public string progress { get; set; }

        public SetSpeedFeedback()
        {
            this.progress = "";
        }

        public SetSpeedFeedback(string progress)
        {
            this.progress = progress;
        }
    }
}
