/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class UploadMissionGoal : Message
    {
        public const string RosMessageName = "isaacs_server/UploadMissionGoal";

        //  Define the goal (parameter)
        public uint id { get; set; }
        public NavSatFix[] waypoints { get; set; }

        public UploadMissionGoal()
        {
            this.id = 0;
            this.waypoints = new NavSatFix[0];
        }

        public UploadMissionGoal(uint id, NavSatFix[] waypoints)
        {
            this.id = id;
            this.waypoints = waypoints;
        }
    }
}
