/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class UploadMissionAction : Action<UploadMissionActionGoal, UploadMissionActionResult, UploadMissionActionFeedback, UploadMissionGoal, UploadMissionResult, UploadMissionFeedback>
    {
        public const string RosMessageName = "isaacs_server/UploadMissionAction";

        public UploadMissionAction() : base()
        {
            this.action_goal = new UploadMissionActionGoal();
            this.action_result = new UploadMissionActionResult();
            this.action_feedback = new UploadMissionActionFeedback();
        }

    }
}
