/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.IsaacsServer;

namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class AllSensorsAvailableResponse : Message
    {
        public const string RosMessageName = "isaacs_server/AllSensorsAvailable";

        public Sensor[] sensors_available { get; set; }
        public string message { get; set; }
        public bool success { get; set; }

        public AllSensorsAvailableResponse()
        {
            this.sensors_available = new Sensor[0];
            this.message = "";
            this.success = false;
        }

        public AllSensorsAvailableResponse(Sensor[] sensors_available, string message, bool success)
        {
            this.sensors_available = sensors_available;
            this.message = message;
            this.success = success;
        }
    }
}
