/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class ControlDroneResponse : Message
    {
        public const string RosMessageName = "isaacs_server/ControlDrone";

        public bool success { get; set; }
        public string message { get; set; }
        public uint id { get; set; }

        public ControlDroneResponse()
        {
            this.success = false;
            this.message = "";
            this.id = 0;
        }

        public ControlDroneResponse(bool success, string message, uint id)
        {
            this.success = success;
            this.message = message;
            this.id = id;
        }
    }
}
