/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.IsaacsServer;

namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class QueryTopicsResponse : Message
    {
        public const string RosMessageName = "isaacs_server/QueryTopics";

        public uint id { get; set; }
        public TopicTypes[] all_topics { get; set; }
        public string message { get; set; }
        public bool success { get; set; }

        public QueryTopicsResponse()
        {
            this.id = 0;
            this.all_topics = new TopicTypes[0];
            this.message = "";
            this.success = false;
        }

        public QueryTopicsResponse(uint id, TopicTypes[] all_topics, string message, bool success)
        {
            this.id = id;
            this.all_topics = all_topics;
            this.message = message;
            this.success = success;
        }
    }
}
