/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class RegisterDroneRequest : Message
    {
        public const string RosMessageName = "isaacs_server/RegisterDrone";

        public string drone_name { get; set; }
        public string drone_type { get; set; }

        public RegisterDroneRequest()
        {
            this.drone_name = "";
            this.drone_type = "";
        }

        public RegisterDroneRequest(string drone_name, string drone_type)
        {
            this.drone_name = drone_name;
            this.drone_type = drone_type;
        }
    }
}
