/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class RegisterSensorRequest : Message
    {
        public const string RosMessageName = "isaacs_server/RegisterSensor";

        public string sensor_name { get; set; }
        public string sensor_type { get; set; }
        public string parent_drone_name { get; set; }

        public RegisterSensorRequest()
        {
            this.sensor_name = "";
            this.sensor_type = "";
            this.parent_drone_name = "";
        }

        public RegisterSensorRequest(string sensor_name, string sensor_type, string parent_drone_name)
        {
            this.sensor_name = sensor_name;
            this.sensor_type = sensor_type;
            this.parent_drone_name = parent_drone_name;
        }
    }
}
