/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class SetSpeedRequest : Message
    {
        public const string RosMessageName = "isaacs_server/SetSpeed";

        public uint id { get; set; }
        public float speed { get; set; }

        public SetSpeedRequest()
        {
            this.id = 0;
            this.speed = 0.0f;
        }

        public SetSpeedRequest(uint id, float speed)
        {
            this.id = id;
            this.speed = speed;
        }
    }
}
