/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.IsaacsServer;

namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class TypeToTopicRequest : Message
    {
        public const string RosMessageName = "isaacs_server/TypeToTopic";

        public uint id { get; set; }
        public TopicTypes[] publishes { get; set; }

        public TypeToTopicRequest()
        {
            this.id = 0;
            this.publishes = new TopicTypes[0];
        }

        public TypeToTopicRequest(uint id, TopicTypes[] publishes)
        {
            this.id = id;
            this.publishes = publishes;
        }
    }
}
