/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class TypeToTopicResponse : Message
    {
        public const string RosMessageName = "isaacs_server/TypeToTopic";

        public bool success { get; set; }
        public string message { get; set; }

        public TypeToTopicResponse()
        {
            this.success = false;
            this.message = "";
        }

        public TypeToTopicResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }
    }
}
