/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.IsaacsServer;

namespace RosSharp.RosBridgeClient.MessageTypes.IsaacsServer
{
    public class Sensor : Message
    {
        public const string RosMessageName = "isaacs_server/Sensor";

        public uint id { get; set; }
        public uint parent_drone_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public TopicTypes[] topics { get; set; }
        public TopicTypes[] services { get; set; }

        public Sensor()
        {
            this.id = 0;
            this.parent_drone_id = 0;
            this.name = "";
            this.type = "";
            this.topics = new TopicTypes[0];
            this.services = new TopicTypes[0];
        }

        public Sensor(uint id, uint parent_drone_id, string name, string type, TopicTypes[] topics, TopicTypes[] services)
        {
            this.id = id;
            this.parent_drone_id = parent_drone_id;
            this.name = name;
            this.type = type;
            this.topics = topics;
            this.services = services;
        }
    }
}
